module.exports = {
  light: 'Light',
  dark: 'Dark',
  meta: {
    title: 'Blog',
    description: '',
  },
  contribute: {
    title: 'Contributors',
    blog: 'Caught a mistake or want to contribute to this blog post?',
    edit_on_github: 'Edit this page on GitHub!',
  },
  pageNotFound: {
    title: 'Page not found',
  },
  toc: {
    title: "On this post"
  },
  footer: {
    links: {
      social: {
        title: 'Social',
      },
      built: {
        title: 'Built with',
      },
    },
  },
  welcome: {
    text: 'You are looking at the default template generated by the'
  },
  backToList: "Back to list"
}
