
name: studio-nuxt-build
run-name: studio nuxt build

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - 'master'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Add write workflow permissions
permissions:
  contents: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build-and-deploy:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        id: pnpm-install
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          version: ${{ matrix.node }}
          cache: ${{ steps.pkgman.outputs.cache }}

      - name: Install dependencies
        run: pnpm install

      - name: Install @nuxthq/studio
        run: pnpm add -D @nuxthq/studio

      - name: Create .nuxtrc
        run: echo $'\nautoImport=true\nmodules[]=@nuxthq/studio' >> .nuxtrc

      - name: Generate
        run: npx nuxi generate
        env:
          NUXT_PUBLIC_STUDIO_API_URL: https://api.nuxt.studio
          NUXT_PUBLIC_STUDIO_TOKENS: fee28560b389806bbce1ab52665243226417b3c44041bb7abdda823d82af9ac2

      - name: Add .nojekyll file
        run: touch .output/public/.nojekyll

        # Deployment job
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
